### ISSUE TITLE
Anderes Kind auswählen

### ISSUE THREAD

**Issue by MultiMediaCoding** [philippdormann/elternportal-api#37]
Hallo, es ist mir zwar möglich die Kinder anzusehen und ich bekomme auch eine ID, wenn ich die Anfrage tätige. Trotzdem habe ich es bisher nicht geschafft z.B. den Schulaufgabenplan ein anderes Kindes abzurufen. 
Egal welche Zahl ist ich für kid einsetzte, ich bekomme nur Informationen über immer dasselbe.

**Comment by philippdormann** [comment]
Das kann gut sein 🤔
Ich habe leider keine Möglichkeit, das zu testen - freue mich natürlich über einen Pull request 😉
