### ISSUE TITLE
Abrufen der Elternbriefe schlägt fehl

### ISSUE THREAD

**Issue by MultiMediaCoding** [philippdormann/elternportal-api#38]
Guten Tag, bei der Nutzung der API ist mir aufgefallen, dass die serverles- function leider immer crasht, wenn ich versuche die Elternbriefe abzurufen.
Es kann gut sein, dass dieser Fehler nur bei mir zutrifft, nachdem sich das Elternportal auf verschiedene Weisen konfigurieren lässt, aus diesem Grund ist auch fraglich, inwiefern diese Informationen hilfreich sind.

### Die Meldung sieht dann in etwa so aus:

This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: fra1::sdgfk-1689165533684-625d5ab2e50e

Ich hoffe diese Informationen sind nützlich, um das Problem ein wenig eingrenzen zu können.

Ich kenne mich zwar nicht sonderlich gut mit JavaScript aus, beherrsche aber Flutter & Dart - welches der Sprache ein wenig ähnelt - und wäre bereit zu versuchen das Problem zu beben.
Allerdings habe ich bis zum jetzigen Zeitpunkt keinerlei Erfahrungen mit GitHub gesammelt und habe keine Vorstellung davon, wie man den Code am besten in VS Code Debugger kann.

Es wäre erfreulich, wenn jemand dabei weiterhelfen könnte.

**Comment by philippdormann** [comment]
Hi @MultiMediaCoding 

die vercel serverless function wurde zuletzt am 27.09.2022 geupdated, läuft leider in request timeouts auf elternportal-Seite und wurde daher aus der README entfernt.
Das npm-package (siehe README) funktioniert perfekt 😉

**Comment by MultiMediaCoding** [comment]
Guten Tag und danke für deine Antwort!

Ist es vielleicht trotzdem möglich, die API auf einer anderen Platform zu hosten, auf welcher die Anfrage nicht durch Request timeouts ausläuft?

Ich würde die API nämlich gerne in einer Flutter App nutzen und dort ist es eben nicht möglich von dem Package Gebrauch zu machen.
