### ISSUE TITLE
getTermine ignoriert from und to

### ISSUE THREAD

**Issue by pimisen** [philippdormann/elternportal-api#42]
HI @philippdormann, 
Die getTermine Funktion ingnoiert from und to und liefert immer alle Termine. (Ich schicke Unix Milliseconds als Werte für from und to).
Der direkte Aufruf von https://${this.short}.eltern-portal.org/api/ws_get_termine.php?from=timestamp&to=timestamp liefert aber auch nicht das gewünschte, obwohl das Portal diese Requests zur Kalenderanzeige selbst benutzt.
Ich habe mehrere Kinder und müsste je Kind nur die Tests und Schulaufgaben abrufen ("class":"event-warning" und "class":"event-alert"), "class":"event-info" hingegen soll nicht im Ergebnis ankommen.

Das Ziel ist die Einträge möglichst 1x täglich automatisiert in den Google Familienkalender einzutragen.

Wie kann ich das hinbekommen?
Ich verstehe ein wenig von dem Code- und node.js-Zeug, aber selbst coden und commiten übersteigt meine DEV-Fähigkeiten :-( 

Ich würde aber unsere ${this.short} und die Zugangsdaten per PN zum Testen zur Verfügung stellen!
Oder gibt es vielleicht eine Postman Collection zum rum spielen?

Grüße aus 85375
Michi

**Comment by philippdormann** [comment]
Hi Michi @pimisen 

Mit dem neuesten [release v2.1.3](https://github.com/philippdormann/elternportal-api/releases/tag/2.1.3) sollte die `getTermine` Funktion auch entsprechend die Ergebnisse filtern.
Dabei ist jetzt egal, ob du UNIX Seconds/ Milliseconds mitgibst.

**Comment by pimisen** [comment]
Hi Philip @philippdormann unglücklicherweise liefert er mir jetzt gar keine Termine mehr zuück.
Ich gehe mit den u.g. Timestamps rein, da sollten einige hundert Termine zurückkommen.
Das zweite ist die leider leere Ausgabe von getKids()

`node test.mjs 
(node:369730) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
1696094514188
1708686514188
[ { name: '', id: NaN } ]
[]
`
Mein Code (Ohne die Credentials)

`//var beginn = new Date().valueOf();
//var ende = new Date(beginn+2592000000).valueOf();
var beginn=1696094514188;
var ende=1708686514188;
const termine = await client.getTermine(beginn,ende);
//const termine = await client.getTermine();
const kinder = await client.getKids();
console.log(beginn);
console.log(ende);
console.log(kinder);
console.log(termine);`
