### ISSUE TITLE
getTermine() gibt ein leeres Array zurrück

### ISSUE THREAD

**Issue by MultiMediaCoding** [philippdormann/elternportal-api#46]
Beim Aufrufen von getTermine() in der neusten Version der API, wird lediglich `[]` zurückgegeben.

**Comment by philippdormann** [comment]
Teste gerne mal das neue [release 2.4.0](https://github.com/philippdormann/elternportal-api/releases/tag/2.4.0) - sollte gefixed sein😉

**Comment by MultiMediaCoding** [comment]
Super, funktioniert wieder 👍
