### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by dxkyy** [philippdormann/elternportal-api#52]
Dies ist mein Code:
```ts
import { getElternportalClient } from "@philippdormann/elternportal-api";

const client = await getElternportalClient({
  short,
  username,
  password,
  kidId: 0, // Optional
});

const data = await client.getSchoolInfos();
console.log(data);
```
Aber wenn ich den Code ausführe, kommt das:
```
Failed to set kid to: 0
[]
```

Ich habe auch probiert die Id zu 1 oder so zu ändern, aber das hat nichts gebracht.

**Comment by philippdormann** [comment]
wie in #49 erwähnt, habe ich leider keinen Account mehr und kann das nicht testen...
@MultiMediaCoding kannst du dir das anschauen/ erklären?

**Comment by MultiMediaCoding** [comment]
Ja, ich schaue es mir mal 👍

**Comment by MultiMediaCoding** [comment]
Eigentlich müsste id=0 den Account des jüngsten Kindes nutzen.
@dxkyy hast du versucht die getKids Funktion aufzurufen und dann die id daraus zu verwenden?

**Comment by dxkyy** [comment]
```ts
const client = await getElternportalClient({
	short,
	username,
	password,
});

const data = await client.getKids();
console.log(data);
```
Ergibt immer noch das hier: 
```
Failed to set kid to: 0
[]
```

**Comment by MultiMediaCoding** [comment]
Ich habe mit meinem Account nochmal diesen Code getestet und korrekte Daten bekommen: 

```
const client = await getElternportalClient({
    short: "short",
    username: "username",
    password: "password",
    kidId: 0,
  });

client.getSchoolInfos().then((schoolInfo) => {
    console.log(schoolInfo);
 });
```
Kannst du mal schauen, ob dein Elternportal die setKid Funktion beim Auswählen eines Kindes aufruft?

**Comment by MultiMediaCoding** [comment]
Hast du mal in die Network Requests bei deinem Elternportal geschaut?

Ich kann das leider nicht testen, weil bei meinem Account eine setChild() Methode problemlos aufgerufen wird. 
Das sieht dann so aus:

**Request-URL:** `https://kürzel.eltern-portal.org/api/set_child.php?id=16`

<img width="351" alt="Kind auswählen" src="https://github.com/user-attachments/assets/e626acab-1011-486f-8748-e76532b48529">


Falls die GET-Request bei dir nicht auftaucht, könnte man nämlich bei dem Fehler ganz regulär fortfahren und sich wie in vorherigen Versionen authentifizieren.

**Comment by dxkyy** [comment]
Was muss ich machen, damit diese Request ausgeführt wird? Ich sehe die nicht bei meinem Network tab

**Comment by MultiMediaCoding** [comment]
Du musst ein Kind auswählen.

**Comment by philippdormann** [comment]
Nachdem der Issue mittlerweile 1 Monat inaktiv ist, werte ich das Problem als gelöst
